// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vheyvrxzxbkdmhcpbswh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZoZXl2cnh6eGJrZG1oY3Bic3doIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMzc2OTUsImV4cCI6MjA2MDkxMzY5NX0.GTPjAsyN3rKLy40kB6-oLBZ9BdX8XzmDiJdcxbStxtU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);